id: IAA20E4FA
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 17:58:35.820279+00:00
last_modified: 2022-12-14 17:58:35.820287+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-068-005
  eft-text-version: 1.1.5 2020
  title: Toh_271-The_Eight_Buddhas-v2
bases:
  '1038':
    source_metadata: null
    order: 1
    base_file: 1038.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
